import { ArrowRight, BookOpen, CircleAlert, HeartPulse, PersonStanding, TimerReset } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Reveal } from '../components/Reveal'

const articles = [
  { category: 'Pain science', title: 'Feeling better is not the finish line—and that is good news', excerpt: 'Why symptom relief and rebuilding physical capacity are related, but not identical, goals.', icon: TimerReset },
  { category: 'Training', title: 'What “start where you are” actually looks like', excerpt: 'A practical way to choose load, range, and volume without waiting to feel perfect.', icon: PersonStanding },
  { category: 'Bone health', title: 'Strength training when bone health is the goal', excerpt: 'An introduction to progressive resistance, balance practice, and appropriately selected impact.', icon: HeartPulse },
]

export function LearnPage() {
  return (
    <main>
      <section className="page-hero"><div className="mx-auto grid max-w-[1480px] gap-10 px-5 sm:px-8 lg:grid-cols-[1.1fr_0.9fr] lg:items-end lg:px-12"><Reveal><p className="eyebrow">Learn to move with context</p><h1 className="page-title mt-6">Understanding builds confidence.</h1></Reveal><Reveal delay={0.08}><p className="max-w-xl text-xl leading-relaxed text-[#53615e]">Clear, practical education about symptoms, exercise, and progression—without fear-based language or one-size-fits-all answers.</p></Reveal></div></section>

      <section className="pb-24 lg:pb-32"><div className="mx-auto max-w-[1480px] px-5 sm:px-8 lg:px-12"><Reveal className="relative overflow-hidden rounded-[2.2rem] bg-[#101817] px-6 py-12 text-white sm:px-10 lg:grid lg:grid-cols-[1fr_0.8fr] lg:items-center lg:px-16 lg:py-16"><div><span className="grid size-12 place-items-center rounded-full bg-[#00a6b4]"><BookOpen className="size-6" /></span><p className="eyebrow mt-9 text-[#6de1e8]">Featured guide</p><h2 className="mt-5 max-w-3xl text-4xl font-black tracking-[-0.055em] sm:text-6xl">Understand your symptoms without jumping to a diagnosis.</h2><p className="mt-6 max-w-2xl text-lg leading-relaxed text-white/60">Explore common musculoskeletal complaints, questions worth asking, and signs that mean it is time to seek professional care.</p><Link to="/symptoms" className="mt-8 flex w-fit items-center gap-3 font-bold text-[#75e1e8]">Open the symptom guide <ArrowRight className="size-5" /></Link></div><div className="relative mt-10 min-h-[260px] lg:mt-0"><div className="absolute right-0 top-1/2 size-72 -translate-y-1/2 rounded-full border-[70px] border-[#00a6b4]/15" /><div className="absolute right-24 top-12 size-36 rounded-full border border-white/15" /></div></Reveal></div></section>

      <section className="section-space bg-white"><div className="mx-auto max-w-[1480px] px-5 sm:px-8 lg:px-12"><Reveal><p className="eyebrow">From the library</p><h2 className="section-title mt-5 max-w-4xl">Less noise. More useful understanding.</h2></Reveal><div className="mt-12 grid gap-5 lg:grid-cols-3">{articles.map((article, index) => { const Icon = article.icon; return <Reveal key={article.title} delay={index * 0.08} className="group flex min-h-[360px] flex-col rounded-[1.8rem] border border-black/8 bg-[#f4f4ef] p-7 transition hover:-translate-y-1 hover:shadow-xl"><div className="flex items-center justify-between"><span className="grid size-11 place-items-center rounded-full bg-[#dcefeb] text-[#008d99]"><Icon className="size-5" /></span><span className="text-xs text-black/30">0{index + 1}</span></div><div className="mt-auto"><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#008d99]">{article.category}</p><h3 className="mt-4 text-2xl font-black leading-tight tracking-[-0.045em]">{article.title}</h3><p className="mt-4 leading-relaxed text-[#63706c]">{article.excerpt}</p><span className="mt-7 flex items-center gap-2 text-sm font-bold">Read the guide <ArrowRight className="size-4 transition group-hover:translate-x-1" /></span></div></Reveal>})}</div></div></section>

      <section className="section-space mx-auto max-w-[1180px] px-5 sm:px-8"><Reveal className="grid gap-8 rounded-[2rem] border border-[#dbb883] bg-[#fff5e6] p-7 sm:p-10 lg:grid-cols-[auto_1fr] lg:items-start"><span className="grid size-12 place-items-center rounded-full bg-[#f5d8aa] text-[#8b5a19]"><CircleAlert className="size-6" /></span><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#8b5a19]">A note about health information</p><h2 className="mt-3 text-2xl font-black tracking-[-0.04em]">Education can guide your next question. It cannot diagnose your condition.</h2><p className="mt-4 leading-relaxed text-[#6a5940]">The information on RE:FORM is general and does not replace an examination or individualized advice. Seek urgent care for severe or rapidly worsening symptoms, chest pain, major trauma, new loss of strength, or changes in bladder or bowel control.</p><Link to="/symptoms" className="mt-6 flex w-fit items-center gap-2 font-bold text-[#70460f]">Review urgent signs <ArrowRight className="size-4" /></Link></div></Reveal></section>
    </main>
  )
}
